allow-branch = ["main"]
sign-commit = false
sign-tag = false
push-remote = "origin"
release = true
publish = true
verify = true
push = true
push-options = []
shared-version = true
consolidate-commits = false
pre-release-commit-message = "(cargo-release) version {{version}}"
tag-message = "(cargo-release) {{crate_name}} version {{version}}"
tag-name = "{{prefix}}v{{version}}"
tag = false
enable-features = []
enable-all-features = false
dependent-version = "fix"
